name: Enforce Pull Request Title includes Jira Issue Key
description: Check that a PR title starts with a Jira Issue Key
inputs:
  projectKey:
    description: 'A specific Jira Project Key that must be included.'
    required: false
  ciExclusion: 
    description: 'A specific string suffix that may be affixed to the projectKey instead of an Issue Key.'
    required: false
    default: "CI"
  exclusionMarker:
    description: 'A specific string prefix that will automatically pass the title, regardless of projectKey and Issue Key.'
    required: false
    default: "!"
runs:
  using: node12
  main: dist/index.js